version: '3.8'
services:
    api:
        build:
            context: ./api
            dockerfile: Dockerfile
        image: ph-api:dev
        container_name: ph-api
        ports:
            - "3001:3001"
        volumes:
            - ./api/src:/usr/src/api/src
        environment: 
            - ROCKET_PORT=3001
            - ROCKET_ADDRESS=0.0.0.0

    app:
        tty: true
        build:
            context: ./app
            dockerfile: Dockerfile
        image: ph-app:dev
        container_name: ph-app
        depends_on: 
            - api
        ports:
            - "3000:3000"
        volumes:
            - ./app:/app
        environment: 
            - CHOKIDAR_USEPOLLING=true
            - REACT_APP_API_URL=http://0.0.0.0:3001
    