version: '3.8'
services:
    api:
        build:
            context: ./api
            dockerfile: Dockerfile.prod
        image: ph-api:prod
        container_name: ph-api-prod
        ports:
            - "4001:4001"
        environment: 
            - ROCKET_ENV=production
            - ROCKET_PORT=4001
            - ROCKET_ADDRESS=0.0.0.0
        restart: always

    app:
        tty: true
        build:
            context: ./app
            dockerfile: Dockerfile.prod
        image: ph-app:prod
        container_name: ph-app-prod
        depends_on: 
            - api
        ports:
            - "80:80"
        environment:
            - REACT_APP_API_URL=http://0.0.0.0:4001
        volumes:
            - ./app:/app
        restart: always